/*create landing area table - WRK_CUSTOMERS*/
drop table WRK_CUSTOMERS;

create table WRK_CUSTOMERS
(
ID	NUMBER(4,0),
NAME	VARCHAR2(26 BYTE),
USERNAME	VARCHAR2(26 BYTE),
EMAIL	VARCHAR2(128 BYTE),
DATEOFBIRTH	DATE,
STREETADDRESS	VARCHAR2(128 BYTE),
CITY	VARCHAR2(26 BYTE),
COUNTRY	VARCHAR2(26 BYTE),
ZIP	VARCHAR2(26 BYTE),
STATE	VARCHAR2(26 BYTE),
PHONE	VARCHAR2(26 BYTE)
);

/*create landing area table - WRK_PRODUCTS*/
drop table WRK_PRODUCTS;

create table WRK_PRODUCTS
(
PRODUCTS	NUMBER(7,0),
PRODUCTNAME	VARCHAR2(128 BYTE),
COMPANYNAME	VARCHAR2(128 BYTE),
PRICE	NUMBER(7,2),
WAREHOUSELOCATIONSTATE	VARCHAR2(26 BYTE)
);

/*create landing area table - WRK_FCT_PURCHASE*/
drop table WRK_FCT_PURCHASE;

create table WRK_FCT_PURCHASE
(
PAYMENTID	NUMBER(9,0),
CUSTOMERID	NUMBER(5,0),
PRODUCTID	NUMBER(7,0),
TRANSACTIONDATE	VARCHAR2(26 BYTE),
CREDITCARD	VARCHAR2(26 BYTE),
CREDITCARDNUMBER	VARCHAR2(26 BYTE)
);