/*create fct_table - cls_fct_purchase*/
drop table CLS_FCT_PURCHASE;

CREATE TABLE CLS_FCT_PURCHASE
(
SK NUMBER(10,0),
PAYMENTID	NUMBER(9,0),
CUSTOMERID	NUMBER(5,0),
PRODUCTID	NUMBER(7,0),
TRANSACTIONDATE	VARCHAR2(26 BYTE),
CREDITCARD	VARCHAR2(26 BYTE),
CREDITCARDNUMBER	VARCHAR2(26 BYTE),
ISINTERSTATE NUMBER(1,0)
);